#!/usr/bin/env bash
# This script displays username, useserID, and home directory for user
while IFS=: read -r username _ userid _ _ homedir _
do
  echo "$username:$userid:$homedir"
done < /etc/passwd
