#!/usr/bin/env bash
# Script that prints best School 10 times but displays best school and hi
count=1
while [ $count -le 10 ]
do
  if [ $count -eq 9 ]
  then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((count++))
done
