#!/usr/bin/env bash
#Code displays bad luck on loop 4,good luck on loop 8 and best school for the rest
count=1
while [ $count -le 10 ]
do
  if [ $count -eq 4 ]
  then
    echo "bad luck"
  elif [ $count -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  ((count++))
done
